# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 176)
        self.LoginLabel = QtWidgets.QLabel(Dialog)
        self.LoginLabel.setGeometry(QtCore.QRect(160, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setObjectName("LoginLabel")
        self.EmailLabel = QtWidgets.QLabel(Dialog)
        self.EmailLabel.setGeometry(QtCore.QRect(10, 50, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.EmailLabel.setFont(font)
        self.EmailLabel.setObjectName("EmailLabel")
        self.PassLabel = QtWidgets.QLabel(Dialog)
        self.PassLabel.setGeometry(QtCore.QRect(10, 80, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PassLabel.setFont(font)
        self.PassLabel.setObjectName("PassLabel")
        self.EmailEntry = QtWidgets.QLineEdit(Dialog)
        self.EmailEntry.setGeometry(QtCore.QRect(120, 50, 271, 21))
        self.EmailEntry.setObjectName("EmailEntry")
        self.PassEntry = QtWidgets.QLineEdit(Dialog)
        self.PassEntry.setGeometry(QtCore.QRect(120, 80, 271, 21))
        self.PassEntry.setObjectName("PassEntry")
        self.LoginButton = QtWidgets.QPushButton(Dialog)
        self.LoginButton.setGeometry(QtCore.QRect(130, 110, 251, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LoginButton.setFont(font)
        self.LoginButton.setObjectName("LoginButton")
        self.LoginButton_2 = QtWidgets.QPushButton(Dialog)
        self.LoginButton_2.setGeometry(QtCore.QRect(0, 110, 101, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LoginButton_2.setFont(font)
        self.LoginButton_2.setObjectName("LoginButton_2")
        self.WrongData = QtWidgets.QLabel(Dialog)
        self.WrongData.setGeometry(QtCore.QRect(280, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.WrongData.setFont(font)
        self.WrongData.setObjectName("WrongData")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LoginLabel.setText(_translate("Dialog", "Login"))
        self.EmailLabel.setText(_translate("Dialog", "E-Mail:"))
        self.PassLabel.setText(_translate("Dialog", "Passwort:"))
        self.LoginButton.setText(_translate("Dialog", "Login"))
        self.LoginButton_2.setText(_translate("Dialog", "Regristrieren"))
        self.WrongData.setText(_translate("Dialog", "Falsche Info(s)"))
