from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 215)
        self.newEmailLabel = QtWidgets.QLabel(Dialog)
        self.newEmailLabel.setGeometry(QtCore.QRect(30, 40, 58, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.newEmailLabel.setFont(font)
        self.newEmailLabel.setObjectName("newEmailLabel")
        self.newPassLabel = QtWidgets.QLabel(Dialog)
        self.newPassLabel.setGeometry(QtCore.QRect(10, 70, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.newPassLabel.setFont(font)
        self.newPassLabel.setObjectName("newPassLabel")
        self.newEmailEntry = QtWidgets.QLineEdit(Dialog)
        self.newEmailEntry.setGeometry(QtCore.QRect(100, 40, 271, 21))
        self.newEmailEntry.setObjectName("newEmailEntry")
        self.newPassEntry = QtWidgets.QLineEdit(Dialog)
        self.newPassEntry.setGeometry(QtCore.QRect(100, 70, 271, 21))
        self.newPassEntry.setObjectName("newPassEntry")
        self.newPassEntry_2 = QtWidgets.QLineEdit(Dialog)
        self.newPassEntry_2.setGeometry(QtCore.QRect(100, 100, 271, 21))
        self.newPassEntry_2.setObjectName("newPassEntry_2")
        self.newPassLabel_2 = QtWidgets.QLabel(Dialog)
        self.newPassLabel_2.setGeometry(QtCore.QRect(10, 100, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.newPassLabel_2.setFont(font)
        self.newPassLabel_2.setObjectName("newPassLabel_2")
        self.titleLabel = QtWidgets.QLabel(Dialog)
        self.titleLabel.setGeometry(QtCore.QRect(160, 10, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(130, 140, 201, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 140, 88, 34))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.newEmailLabel.setText(_translate("Dialog", "E-Mail:"))
        self.newPassLabel.setText(_translate("Dialog", "Passwort:"))
        self.newPassLabel_2.setText(_translate("Dialog", "Bestätige:"))
        self.titleLabel.setText(_translate("Dialog", "Register"))
