# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TodoAppWin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 543)
        self.TitleLabel = QtWidgets.QLabel(Dialog)
        self.TitleLabel.setGeometry(QtCore.QRect(290, 20, 161, 18))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.Todo1 = QtWidgets.QLabel(Dialog)
        self.Todo1.setGeometry(QtCore.QRect(40, 60, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo1.setFont(font)
        self.Todo1.setObjectName("Todo1")
        self.Todo8 = QtWidgets.QLabel(Dialog)
        self.Todo8.setGeometry(QtCore.QRect(40, 270, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo8.setFont(font)
        self.Todo8.setObjectName("Todo8")
        self.Todo7 = QtWidgets.QLabel(Dialog)
        self.Todo7.setGeometry(QtCore.QRect(40, 240, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo7.setFont(font)
        self.Todo7.setObjectName("Todo7")
        self.Todo6 = QtWidgets.QLabel(Dialog)
        self.Todo6.setGeometry(QtCore.QRect(40, 210, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo6.setFont(font)
        self.Todo6.setObjectName("Todo6")
        self.Todo5 = QtWidgets.QLabel(Dialog)
        self.Todo5.setGeometry(QtCore.QRect(40, 180, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo5.setFont(font)
        self.Todo5.setObjectName("Todo5")
        self.Todo4 = QtWidgets.QLabel(Dialog)
        self.Todo4.setGeometry(QtCore.QRect(40, 150, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo4.setFont(font)
        self.Todo4.setObjectName("Todo4")
        self.Todo3 = QtWidgets.QLabel(Dialog)
        self.Todo3.setGeometry(QtCore.QRect(40, 120, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo3.setFont(font)
        self.Todo3.setObjectName("Todo3")
        self.Todo2 = QtWidgets.QLabel(Dialog)
        self.Todo2.setGeometry(QtCore.QRect(40, 90, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo2.setFont(font)
        self.Todo2.setObjectName("Todo2")
        self.Todo9 = QtWidgets.QLabel(Dialog)
        self.Todo9.setGeometry(QtCore.QRect(40, 300, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo9.setFont(font)
        self.Todo9.setObjectName("Todo9")
        self.Todo11 = QtWidgets.QLabel(Dialog)
        self.Todo11.setGeometry(QtCore.QRect(40, 360, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo11.setFont(font)
        self.Todo11.setObjectName("Todo11")
        self.Todo12 = QtWidgets.QLabel(Dialog)
        self.Todo12.setGeometry(QtCore.QRect(40, 390, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo12.setFont(font)
        self.Todo12.setObjectName("Todo12")
        self.Todo13 = QtWidgets.QLabel(Dialog)
        self.Todo13.setGeometry(QtCore.QRect(40, 420, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo13.setFont(font)
        self.Todo13.setObjectName("Todo13")
        self.Todo15 = QtWidgets.QLabel(Dialog)
        self.Todo15.setGeometry(QtCore.QRect(40, 480, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo15.setFont(font)
        self.Todo15.setObjectName("Todo15")
        self.Todo14 = QtWidgets.QLabel(Dialog)
        self.Todo14.setGeometry(QtCore.QRect(40, 450, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo14.setFont(font)
        self.Todo14.setObjectName("Todo14")
        self.Todo10 = QtWidgets.QLabel(Dialog)
        self.Todo10.setGeometry(QtCore.QRect(40, 330, 401, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Todo10.setFont(font)
        self.Todo10.setObjectName("Todo10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.TitleLabel.setText(_translate("Dialog", "Deine Todos:"))
        self.Todo1.setText(_translate("Dialog", "TextLabel"))
        self.Todo8.setText(_translate("Dialog", "TextLabel"))
        self.Todo7.setText(_translate("Dialog", "TextLabel"))
        self.Todo6.setText(_translate("Dialog", "TextLabel"))
        self.Todo5.setText(_translate("Dialog", "TextLabel"))
        self.Todo4.setText(_translate("Dialog", "TextLabel"))
        self.Todo3.setText(_translate("Dialog", "TextLabel"))
        self.Todo2.setText(_translate("Dialog", "TextLabel"))
        self.Todo9.setText(_translate("Dialog", "TextLabel"))
        self.Todo11.setText(_translate("Dialog", "TextLabel"))
        self.Todo12.setText(_translate("Dialog", "TextLabel"))
        self.Todo13.setText(_translate("Dialog", "TextLabel"))
        self.Todo15.setText(_translate("Dialog", "TextLabel"))
        self.Todo14.setText(_translate("Dialog", "TextLabel"))
        self.Todo10.setText(_translate("Dialog", "TextLabel"))

